# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceList_choice', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=300)),
                ('event_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['event_id'],
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventMember_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Event')),
            ],
            options={
                'db_table': 'eventMembers',
            },
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('serviceUser_id', models.IntegerField(primary_key=True, serialize=False)),
                ('serviceUser_firstName', models.CharField(max_length=100)),
                ('serviceUser_lastName', models.CharField(max_length=100)),
                ('serviceUser_token', models.CharField(max_length=200)),
                ('serviceUser_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'serviceUsers',
                'ordering': ['serviceUser_lastName'],
            },
        ),
        migrations.CreateModel(
            name='ShownUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shownUserList_shownUsers', models.ManyToManyField(related_name='shownUsers', to='meetings.EventMember')),
                ('shownUserList_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.EventMember')),
            ],
        ),
        migrations.CreateModel(
            name='VisitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitList_whoVisit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoVisit', to='meetings.EventMember')),
                ('visitList_whomVisit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whomVisit', to='meetings.EventMember')),
            ],
        ),
        migrations.AddField(
            model_name='eventmember',
            name='eventMember_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.ServiceUser'),
        ),
        migrations.AddField(
            model_name='choicelist',
            name='choiceList_whoChoosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoChoosen', to='meetings.ServiceUser'),
        ),
        migrations.AddField(
            model_name='choicelist',
            name='choiceList_whomChoosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whomChoosen', to='meetings.EventMember'),
        ),
    ]
