# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('eventMember_id', models.IntegerField(primary_key=True, serialize=False)),
                ('eventMember_firstName', models.CharField(max_length=100)),
                ('eventMember_lastName', models.CharField(max_length=100)),
                ('eventMember_token', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['eventMember_lastName'],
                'db_table': 'eventMembers',
            },
        ),
    ]
