# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChoiceList',
            new_name='Choice',
        ),
    ]
