# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_eventmember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['event_name'],
                'db_table': 'events',
            },
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_members',
            field=models.ManyToManyField(to='meetings.EventMember'),
        ),
    ]
