# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20170827_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceList_whoChosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoChosen', to='meetings.ServiceUser'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceList_whomChosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whomChosen', to='meetings.EventMember'),
        ),
    ]
