# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='eventMember_dislikes',
            field=models.ManyToManyField(related_name='_eventmember_eventMember_dislikes_+', to='meetings.EventMember'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='eventMember_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='eventMember_likes',
            field=models.ManyToManyField(related_name='_eventmember_eventMember_likes_+', to='meetings.EventMember'),
        ),
    ]
