# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20170809_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions_choice', models.NullBooleanField()),
                ('actions_visit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extendedUser_actions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.Actions')),
                ('extendedUser_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.Event')),
                ('extendedUser_relatedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extendedUsers', to='meetings.EventMember')),
                ('extendedUser_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.EventMember')),
            ],
            options={
                'db_table': 'extendedUsers',
            },
        ),
    ]
