# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20170811_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='extendedUser_actions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Actions'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='extendedUser_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Event'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='extendedUser_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.EventMember'),
        ),
    ]
