# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_auto_20170811_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='extendedUser_hide',
            field=models.BooleanField(default=False),
        ),
    ]
