# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_extendeduser_extendeduser_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceList_choice', models.BooleanField()),
                ('choiceList_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ShownUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VisitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='extendedUser_actions',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='extendedUser_event',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='extendedUser_relatedUser',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='extendedUser_user',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='eventMember_dislikes',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='eventMember_likes',
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
        migrations.AddField(
            model_name='visitlist',
            name='visitList_whoVisit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoVisit', to='meetings.EventMember'),
        ),
        migrations.AddField(
            model_name='visitlist',
            name='visitList_whomVisit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whomVisit', to='meetings.EventMember'),
        ),
        migrations.AddField(
            model_name='shownuserlist',
            name='shownUserList_shownUsers',
            field=models.ManyToManyField(related_name='shownUsers', to='meetings.EventMember'),
        ),
        migrations.AddField(
            model_name='shownuserlist',
            name='shownUserList_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.EventMember'),
        ),
        migrations.AddField(
            model_name='choicelist',
            name='choiceList_whoChoosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoChoosen', to='meetings.EventMember'),
        ),
        migrations.AddField(
            model_name='choicelist',
            name='choiceList_whomChoosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whomChoosen', to='meetings.EventMember'),
        ),
    ]
